- name: install nginx
  ansible.builtin.apt:
    state: latest
    pkg:
      - nginx
  become: yes
- name: install cowsay
  ansible.builtin.apt:
    name: cowsay
    state: present

- name: cowsay say
  shell: /usr/games/cowsay hello
  become: yes
  register: cow_say

- debug: msg="{{ cow_say.stdout }}"

