- hosts: testservers
  vars:
    root_dir: /var/tmp/www
    nginx_port: 80

  tasks:
   - name: install nginx
     ansible.builtin.apt:
       name: nginx
       state: latest
     become: yes
   - name: update nginix config
     ansible.builtin.template:
       src: files/nginx.conf.j2
       dest: "/etc/nginx/nginx.conf"
     become: yes
     notify:
       - restart nginx
   - name: Create a directory if it does not exist
     ansible.builtin.file:
       path: "{{root_dir}}"
       state: directory
       mode: '0755'
   - name: update index.html
     ansible.builtin.copy:
       src: files/index.html
       dest: "{{root_dir}}/index.html"
     become: yes

  handlers:
   - name: restart nginx
     ansible.builtin.service:
       name: nginx
       state: restarted
     become: yes

